# fly.toml app configuration file generated for htmx-vt-test on 2023-09-10T07:59:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "htmx-vt-test"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
